module.exports = "<div class=\"entry-content\"><p>Website terms and conditions are vital to the long-term success and security of your online business, as they outline the rules by which you and your users must abide. Without terms, you could be subject to abusive users, intellectual property theft, and unnecessary litigation.</p>\n" +
  "<p>Our <strong>free terms and conditions template</strong> will help provide your business with the legal protection it deserves. Download the standard template below, or simply copy and paste the text onto your site.</p>\n" +
  "<p>Alternatively, keep reading to learn more about what a terms and conditions agreement is and how to start writing your own.</p>\n" +
  "<section class=\"table-of-contents\">\n" +
  "<p><strong>AGREEMENT TO TERMS</strong></p>\n" +
  "contribute to, or participate in blogs, message boards, online forums, and other functionality, and may provide you with the opportunity to create, submit, post, display, transmit, perform, publish, distribute, or broadcast content and materials to us or on the Site, including but not limited to text, writings, video, audio, photographs, graphics, comments, suggestions, or personal information or other material (collectively, “Contributions”).</p>\n" +
  "<p>Contributions may be viewable by other users of the Site and through third-party websites. As such, any Contributions you transmit may be treated as non-confidential and non-proprietary. When you create or make available any Contributions, you thereby represent and warrant that:</p>\n" +
  "<ol>\n" +
  "<li>the creation, distribution, transmission, public display, or performance, and the accessing, downloading, or copying of your Contributions do not and will not infringe the proprietary rights, including but not limited to the copyright, patent, trademark, trade secret, or moral rights of any third party.</li>\n" +
  "<li>you are the creator and owner of or have the necessary licenses, rights, consents, releases, and permissions to use and to authorize us, the Site, and other users of the Site to use your Contributions in any manner contemplated by the Site and these Terms and Conditions.</li>\n" +
  "<li>you have the written consent, release, and/or permission of each and every identifiable individual person in your Contributions to use the name or likeness of each and every such identifiable individual person to enable inclusion and use of your Contributions in any manner contemplated by the Site and these Terms and Conditions.</li>\n" +
  "<li>your Contributions are not false, inaccurate, or misleading.</li>\n" +
  "<li>your Contributions are not unsolicited or unauthorized advertising, promotional materials, pyramid schemes, chain letters, spam, mass mailings, or other forms of solicitation.</li>\n" +
  "<li>your Contributions are not obscene, lewd, lascivious, filthy, violent, harassing, libelous, slanderous, or otherwise objectionable (as determined by us).</li>\n" +
  "<li>your Contributions do not ridicule, mock, disparage, intimidate, or abuse anyone.</li>\n" +
  "<li>your Contributions do not advocate the violent overthrow of any government or incite, encourage, or threaten physical harm against another.</li>\n" +
  "<li>your Contributions do not violate any applicable law, regulation, or rule.</li>\n" +
  "<li>your Contributions do not violate the privacy or publicity rights of any third party.</li>\n" +
  "<li>your Contributions do not contain any material that solicits personal information from anyone under the age of 18 or exploits people under the age of 18 in a sexual or violent manner.</li>\n" +
  "<li>your Contributions do not violate any federal or state law concerning child pornography, or otherwise intended to protect the health or well-being of minors;</li>\n" +
  "<li>your Contributions do not include any offensive comments that are connected to race, national origin, gender, sexual preference, or physical handicap.</li>\n" +
  "<li>your Contributions do not otherwise violate, or link to material that violates, any provision of these Terms and Conditions, or any applicable law or regulation.</li>\n" +
  "</ol>\n" +
  "<p>Any use of the Site in violation of the foregoing violates these Terms and Conditions and may result in, among other things, termination or suspension of your rights to use the Site.</p>\n" +
  "<p><strong>CONTRIBUTION LICENSE</strong></p>\n" +
  "<p>By posting your Contributions to any part of the Site<span style=\"color: #8351f9;\"> [or making Contributions accessible to the Site by linking your account from the Site to any of your social networking accounts]</span>, you automatically grant, and you represent and warrant that you have the right to grant, to us an unrestricted, unlimited, irrevocable, perpetual, non-exclusive, transferable, royalty-free, fully-paid, worldwide right, and license to host, use, copy, reproduce, disclose, sell, resell, publish, broadcast, retitle, archive, store, cache, publicly perform, publicly display, reformat, translate, transmit, excerpt (in whole or in part), and distribute such Contributions (including, without limitation, your image and voice) for any purpose, commercial, advertising, or otherwise, and to prepare derivative works of, or incorporate into other works, such Contributions, and grant and authorize sublicenses of the foregoing. The use and distribution may occur in any media formats and through any media channels.</p>\n" +
  "<p>This license will apply to any form, media, or technology now known or hereafter developed, and includes our use of your name, company name, and franchise name, as applicable, and any of the trademarks, service marks, trade names, logos, and personal and commercial images you provide. You waive all moral rights in your Contributions, and you warrant that moral rights have not otherwise been asserted in your Contributions.</p>\n" +
  "<p>We do not assert any ownership over your Contributions. You retain full ownership of all of your Contributions and any intellectual property rights or other proprietary rights associated with your Contributions. We are not liable for any statements or representations in your Contributions provided by you in any area on the Site.</p>\n" +
  "<p>You are solely responsible for your Contributions to the Site and you expressly agree to exonerate us from any and all responsibility and to refrain from any legal action against us regarding your Contributions.</p>\n" +
  "<p>We have the right, in our sole and absolute discretion, (1) to edit, redact, or otherwise change any Contributions; (2) to re-categorize any Contributions to place them in more appropriate locations on the Site; and (3) to pre-screen or delete any Contributions at any time and for any reason, without notice. We have no obligation to monitor your Contributions.</p>\n" +
  "<p><strong>GUIDELINES FOR REVIEWS</strong></p>\n" +
  "<p>We may provide you areas on the Site to leave reviews or ratings. When posting a review, you must comply with the following criteria:</p>\n" +
  "<p>(1) you should have firsthand experience with the person/entity being reviewed;</p>\n" +
  "<p>(2) your reviews should not contain offensive profanity, or abusive, racist, offensive, or hate language;</p>\n" +
  "<p>(3) your reviews should not contain discriminatory references based on religion, race, gender, national origin, age, marital status, sexual orientation, or disability;</p>\n" +
  "<p>(4) your reviews should not contain references to illegal activity;</p>\n" +
  "<p>(5) you should not be affiliated with competitors if posting negative reviews;</p>\n" +
  "<p>(6) you should not make any conclusions as to the legality of conduct;</p>\n" +
  "<p>(7) you may not post any false or misleading statements;</p>\n" +
  "<p>(8) you may not organize a campaign encouraging others to post reviews, whether positive or negative.</p>\n" +
  "<p>We may accept, reject, or remove reviews in our sole discretion. We have absolutely no obligation to screen reviews or to delete reviews, even if anyone considers reviews objectionable or inaccurate. Reviews are not endorsed by us, and do not necessarily represent our opinions or the views of any of our affiliates or partners.</p>\n" +
  "<p>We do not assume liability for any review or for any claims, liabilities, or losses resulting from any review. By posting a review, you hereby grant to us a perpetual, non-exclusive, worldwide, royalty-free, fully-paid, assignable, and sublicensable right and license to reproduce, modify, translate, transmit by any means, display, perform, and/or distribute all content relating to reviews.</p>\n" +
  "<p><strong>MOBILE APPLICATION LICENSE</strong></p>\n" +
  "<p><strong>Use License</strong></p>\n" +
  "<p>If you access the Site via a mobile application, then we grant you a revocable, non-exclusive, non-transferable, limited right to install and use the mobile application on wireless electronic devices owned or controlled by you, and to access and use the mobile application on such devices strictly in accordance with the terms and conditions of this mobile application license contained in these Terms and Conditions.</p>\n" +
  "<p>You shall not:</p>\n" +
  "<p>(1) decompile, reverse engineer, disassemble, attempt to derive the source code of, or decrypt the application;</p>\n" +
  "<p>(2) make any modification, adaptation, improvement, enhancement, translation, or derivative work from the application;</p>\n" +
  "<p>(3) violate any applicable laws, rules, or regulations in connection with your access or use of the application;</p>\n" +
  "<p>(4) remove, alter, or obscure any proprietary notice (including any notice of copyright or trademark) posted by us or the licensors of the application;</p>\n" +
  "<p>(5) use the application for any revenue generating endeavor, commercial enterprise, or other purpose for which it is not designed or intended;</p>\n" +
  "<p>(6) make the application available over a network or other environment permitting access or use by multiple devices or users at the same time;</p>\n" +
  "<p>(7) use the application for creating a product, service, or software that is, directly or indirectly, competitive with or in any way a substitute for the application;</p>\n" +
  "<p>(8) use the application to send automated queries to any website or to send any unsolicited commercial e-mail;</p>\n" +
  "<p>(9) use any proprietary information or any of our interfaces or our other intellectual property in the design, development, manufacture, licensing, or distribution of any applications, accessories, or devices for use with the application.</p>\n" +
  "<p><strong>Apple and Android Devices</strong></p>\n" +
  "<p>The following terms apply when you use a mobile application obtained from either the Apple Store or Google Play (each an “App Distributor”) to access the Site:</p>\n" +
  "<p>(1) the license granted to you for our mobile application is limited to a non-transferable license to use the application on a device that utilizes the Apple iOS or Android operating systems, as applicable, and in accordance with the usage rules set forth in the applicable App Distributor’s terms and conditions;</p>\n" +
  "<p>(2) we are responsible for providing any maintenance and support services with respect to the mobile application as specified in the terms and conditions of this mobile application license contained in these Terms and Conditions or as otherwise required under applicable law, and you acknowledge that each App Distributor has no obligation whatsoever to furnish any maintenance and support services with respect to the mobile application;</p>\n" +
  "<p>(3) in the event of any failure of the mobile application to conform to any applicable warranty, you may notify the applicable App Distributor, and the App Distributor, in accordance with its terms and policies, may refund the purchase price, if any, paid for the mobile application, and to the maximum extent permitted by applicable law, the App Distributor will have no other warranty obligation whatsoever with respect to the mobile application;</p>\n" +
  "<p>(4) you represent and warrant that (i) you are not located in a country that is subject to a U.S. government embargo, or that has been designated by the U.S. government as a “terrorist supporting” country and (ii) you are not listed on any U.S. government list of prohibited or restricted parties;</p>\n" +
  "<p>(5) you must comply with applicable third-party terms of agreement when using the mobile application, e.g., if you have a VoIP application, then you must not be in violation of their wireless data service agreement when using the mobile application;</p>\n" +
  "<p>6) you acknowledge and agree that the App Distributors are third-party beneficiaries of the terms and conditions in this mobile application license contained in these Terms and Conditions, and that each App Distributor will have the right (and will be deemed to have accepted the right) to enforce the terms and conditions in this mobile application license contained in these Terms and Conditions against you as a third-party beneficiary thereof.</p>\n"